In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
import math

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive



LIMPIA DE DATOS DESDE 0
---



In [ ]:
alumnos = pd.read_csv('/content/drive/MyDrive/Trash/R210930_JP.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (22) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
alumnos[alumnos['Nombre Departamento Materia'] == 'Prog mejoramiento acad de alum']['Nombre Materia Largo']

alumnos.columns

Index(['Clave\nEjercicio Académico', 'Nombre Campus', 'Desc Nivel Acad Alumno',
       'Clave Major Pgma Acad', 'Ind Plan Tec21', 'Clave Programa Académico',
       'Desc Programa Académico', 'v_Siglas Escuela por Major', 'Matrícula',
       'Nombres', 'Apellido Paterno', 'Apellido Materno', 'Género',
       'Fecha de nacimiento', 'Nacionalidad', 'Puntaje PAA',
       'Nombre preparatoria', 'Promedio preparatoria',
       'Desc Periodo Academico', 'Clave Ejer Admision Alumno',
       'Promedio del ejercicio anterior', 'Promedio acumulado', 'Semestre',
       'v_Clasificación ingreso alumno', 'Unidades Inscritas Ejer',
       'Auditoria Grado del Programa Alumno.Total Uni Acred Plan',
       'Clave Estatus Inscripcion', 'Clave Materia', 'Nombre Materia Largo',
       'Numero Grupo', 'Periodo', 'v_Tipo de materia (UF)',
       'Ind Materia Tec21', 'Ind Materia Life', 'Clave Departamento Materia',
       'Nombre Departamento Materia', 'Horas Clase', 'Horas Laboratorio',
       'Unidades',

In [ ]:
columnas_no_deseadas = [
  'Nombre Campus',
  'Desc Nivel Acad Alumno',
  'Ind Plan Tec21',
  'Desc Programa Académico',
  'Matrícula',
  'Nombres',
  'Apellido Paterno',
  'Apellido Materno',
  'Género',
  'Fecha de nacimiento',
  'Nacionalidad',
  'Nombre preparatoria',
  'Promedio preparatoria',
  'Clave Ejer Admision Alumno',
  'Auditoria Grado del Programa Alumno.Total Uni Acred Plan',
  'Clave Estatus Inscripcion',
  'Nombre Materia Largo',
  'Numero Grupo',
  'Ind Materia Tec21',
  'Nombre Departamento Materia',
  'Crn',
  'Periodo.1',
  'Desc Estatus Insc Grupo',
  'Calificacion Final (Lista)',
  'Valor Calif Final',
  'Calificacion Final Real (HA)'
  'v_Tuvo cambio de calificación?',
  'Clave Beca',
  'Desc Beca',
  'Clave Plan Beca',
  'Nombre Campus',
  'Clave\nEjercicio Académico',
  'Ind Plan Tec21',
  'Ind Materia Life'
  'Auditoria Grado del Programa Alumno.Total Uni Acred Plan',
  'Créditos',
  'Periodo.1',
  'v_Tuvo cambio de calificación?',
  'Clave Major Pgma Acad',
  'Clave Programa Académico',
  'Semestre',
  'Clave Materia',
  'Ind Materia Life',
  # Pendientes
  'Clave Departamento Materia',
  'Desc Plan Beca',
]


columnas_deseadas = []

for c in list(alumnos.columns.array):
  if c not in columnas_no_deseadas:
    columnas_deseadas.append(c)

columnas_deseadas

['Unnamed: 0',
 'v_Siglas Escuela por Major',
 'Puntaje PAA',
 'Desc Periodo Academico',
 'Promedio del ejercicio anterior',
 'Promedio acumulado',
 'v_Clasificación ingreso alumno',
 'Unidades Inscritas Ejer',
 'Periodo',
 'v_Tipo de materia (UF)',
 'Horas Clase',
 'Horas Laboratorio',
 'Unidades',
 'Clave Estatus Insc Grupo',
 'Calificacion Final Real (HA)',
 'Valor Calif Final Real']

In [ ]:
for column in alumnos[columnas_deseadas].columns:
  if len(alumnos[column].unique()) < 10:
    print(column)
    print(alumnos[column].unique())
    print()
  else:
    print(column)
    print(len(alumnos[column].unique()))

v_Siglas Escuela por Major
['EAAD' 'ECSG' 'EIC' 'EN' 'EMCS' 'Programa no clasificado' 'VI' 'EHE']

Puntaje PAA
371
Desc Periodo Academico
['Primer Semestre' nan 'Segundo Semestre' 'Faltan Datos'
 'Pendiente de Calcular' 'Tercer Semestre' 'Cuarto Semestre'
 'Quinto Semestre']

Promedio del ejercicio anterior
2502
Promedio acumulado
3184
v_Clasificación ingreso alumno
['Reingreso' 'Nuevo Ingreso']

Unidades Inscritas Ejer
24
Periodo
['1' '2' '3' '1-3' '1-2' '2-3' 'S/D' nan]

v_Tipo de materia (UF)
['Bloque' 'Materia' 'Semana Tec']

Horas Clase
[ 9  3  0  1 12]

Horas Laboratorio
[0 3 1 4]

Unidades
[ 8.   2.7  5.3  0.  16.  40.  10.7 21.3]

Clave Estatus Insc Grupo
['RE' 'BP' 'BT' 'DW']

Calificacion Final Real (HA)
106
Valor Calif Final Real
102


In [ ]:
promedio = alumnos['Puntaje PAA'].mean()

for index, alumno in alumnos.iterrows():
  if math.isnan(alumno['Puntaje PAA']):
    alumnos.at[index, 'Puntaje PAA'] = int(promedio)
    print(f'{index} - {alumno["Puntaje PAA"]}')
  else: 
    alumnos.at[index, 'Puntaje PAA'] = int(alumno["Puntaje PAA"])
    print(f'{index} - {alumno["Puntaje PAA"]}')
    

In [ ]:
becaGen = r'([0-9]*[0-9])+|100'
beca030 = r'[0-2][0-9]'
beca3070 = r'[3-6][0-9]'
beca70100 = r'[7-9][0-9]'

for index, alumno in alumnos.iterrows():
  b = re.findall(becaGen, str(alumno['Desc Plan Beca']))
  if len(b) > 0:
    alumnos.at[index, 'Desc Plan Beca'] = int(max(b))
    print(f'{index} - {max(b)}')  
  else: 
    alumnos.at[index, 'Desc Plan Beca'] = int(0)
  


In [ ]:
# Limpiar calificaciones no numericas
for index, alumno in alumnos.iterrows():
  try:
    alumnos.at[index, 'Valor Calif Final Real'] = int(alumno['Valor Calif Final Real'])
    # print(f'alumno no borrado {index}')
  except:
    alumnos = alumnos.drop(index = index)
    print(f'alumno borrado {index}')


In [ ]:
alumnos['v_Clasificación ingreso alumno'].unique()

array(['Reingreso', 'Nuevo Ingreso'], dtype=object)

In [ ]:
alumnos = alumnos.dropna()

In [ ]:
periodo_ohe = pd.get_dummies(alumnos['Desc Periodo Academico'])
escuelas_ohe = pd.get_dummies(alumnos['v_Siglas Escuela por Major'])
ingreso_ohe = pd.get_dummies(alumnos['v_Clasificación ingreso alumno'])
preiodo2_ohe = pd.get_dummies(alumnos['Periodo'])
materia_ohe = pd.get_dummies(alumnos['v_Tipo de materia (UF)'])
estatus_ohe = pd.get_dummies(alumnos['Clave Estatus Insc Grupo'])

In [ ]:
alumnos = pd.concat([alumnos, periodo_ohe, escuelas_ohe, ingreso_ohe, preiodo2_ohe, materia_ohe, estatus_ohe], axis=1)
alumnos

In [ ]:
alumnos = alumnos.drop(['Desc Periodo Academico', 'v_Siglas Escuela por Major', 'v_Clasificación ingreso alumno', 'Periodo', 'v_Tipo de materia (UF)', 'Clave Estatus Insc Grupo'], axis=1)


In [ ]:
alumnos = alumnos.drop(['Calificacion Final Real (HA)'], axis=1)

In [ ]:
alumnos.to_csv('checkpoint_final.csv')

## CHECKPOINT FINAL

In [ ]:
from keras.models import Sequential
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical

In [ ]:
!pwd

/content


In [ ]:
alumnos = pd.read_csv('/content/checkpoint_final.csv')

In [ ]:
alumnos = alumnos.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1)

In [ ]:
x = alumnos[alumnos.columns.difference(['Valor Calif Final Real'])]
y = alumnos['Valor Calif Final Real']

In [ ]:
alumnos

Puntaje PAA  Promedio del ejercicio anterior  ...  BP  RE
0            1289.0                            46.06  ...   0   1
1            1289.0                            46.06  ...   0   1
2            1289.0                            46.06  ...   0   1
3            1289.0                            46.06  ...   0   1
4            1289.0                            46.06  ...   0   1
...             ...                              ...  ...  ..  ..
254367       1410.0                            92.50  ...   0   1
254368       1410.0                            92.50  ...   0   1
254369       1350.0                            96.00  ...   0   1
254370       1289.0                             0.00  ...   0   1
254371       1289.0                             0.00  ...   0   1

[254372 rows x 37 columns]

In [ ]:
train_x = x[:int(254372*0.8)].to_numpy().astype('float32')
train_y = y[:int(254372*0.8)].to_numpy().astype('float32')
test_x = x[:int(254372*0.2)].to_numpy().astype('float32')
test_y = y[:int(254372*0.2)].to_numpy().astype('float32')

In [ ]:
train_x[0].shape

(36,)

In [ ]:
!pip install -q -U keras-tuner

     |████████████████████████████████| 98 kB 3.7 MB/s 
ERROR: Operation cancelled by user


In [ ]:
import keras_tuner as kt

In [ ]:
def build_model(hp):
  model = keras.Sequential()
  model.add(keras.layers.Dense(
      hp.Choice('units', [64, 128]),
      activation='relu', input_shape=(36,)))
  for i in range(hp.Int("num_layers", 2, 4, 8)):
        model.add(
            keras.layers.Dense(
                hp.Choice('units_2', [32, 64, 128]),
                activation="relu",
            )
        )
        model.add(keras.layers.Dropout(hp.Choice('dropout_rate', [0.1, 0.2, 0.3])))
  model.add(keras.layers.Dense(1, activation='relu'))
  model.compile(loss='mse', optimizer='adam', metrics=['mse'])
  return model

In [ ]:
tuner = kt.RandomSearch(
    build_model,
    objective='mse',
    max_trials=3)

In [ ]:
tuner.search(train_x, train_y,epochs=50, verbose=1, validation_data=(test_x, test_y))
best_model = tuner.get_best_models()[0]

Trial 2 Complete [00h 23m 47s]
mse: 212.32798767089844

Best mse So Far: 210.1225128173828
Total elapsed time: 00h 48m 10s

Search: Running Trial #3

Hyperparameter    |Value             |Best Value So Far 
units             |128               |128               
num_layers        |2                 |2                 
units_2           |128               |128               
dropout_rate      |0.3               |0.1               

Epoch 1/50
6360/6360 [==============================] - 31s 5ms/step - loss: 546.2796 - mse: 546.2796 - val_loss: 1167.3210 - val_mse: 1167.3210
Epoch 2/50
6360/6360 [==============================] - 28s 4ms/step - loss: 435.9831 - mse: 435.9831 - val_loss: 775.4706 - val_mse: 775.4706
Epoch 3/50
6360/6360 [==============================] - 29s 5ms/step - loss: 310.5353 - mse: 310.5353 - val_loss: 693.4631 - val_mse: 693.4631
Epoch 4/50
6360/6360 [==============================] - 28s 4ms/step - loss: 280.5044 - mse: 280.5044 - val_loss: 428.6047 - val_mse:

In [ ]:
model = tf.keras.models.Sequential([
  # Capa de entrada
  keras.layers.Dense(128, activation='relu', input_shape=(36,)),
  # Capas internas 
  keras.layers.Dense(128, activation="relu"), 
  keras.layers.Dense(128, activation="relu"),

  keras.layers.Dropout(0.1),
  keras.layers.Dense(1, activation='relu')
  ])
model.compile(loss='mse', optimizer='adam', metrics=['mse'])

In [ ]:
model.fit(x=train_x, y=train_y, epochs=100, validation_data=(test_x, test_y), verbose=1)

Epoch 1/100
6360/6360 [==============================] - 32s 5ms/step - loss: 428.0970 - mse: 428.0970 - val_loss: 385.7904 - val_mse: 385.7904
Epoch 2/100
6360/6360 [==============================] - 29s 5ms/step - loss: 331.1635 - mse: 331.1635 - val_loss: 329.2850 - val_mse: 329.2850
Epoch 3/100
6360/6360 [==============================] - 29s 5ms/step - loss: 295.8436 - mse: 295.8436 - val_loss: 249.6599 - val_mse: 249.6599
Epoch 4/100
6360/6360 [==============================] - 29s 5ms/step - loss: 247.7831 - mse: 247.7831 - val_loss: 241.0589 - val_mse: 241.0589
Epoch 5/100
6360/6360 [==============================] - 27s 4ms/step - loss: 254.5152 - mse: 254.5152 - val_loss: 233.2015 - val_mse: 233.2015
Epoch 6/100
6360/6360 [==============================] - 29s 5ms/step - loss: 241.5715 - mse: 241.5715 - val_loss: 229.6668 - val_mse: 229.6668
Epoch 7/100
6360/6360 [==============================] - 29s 5ms/step - loss: 240.2880 - mse: 240.2880 - val_loss: 263.6728 - val_mse: 2

In [ ]:
model.save(('/content/pesosAPIS.h5'))

In [ ]:
# test_x[0].reshape(-1, 36).shape
# np.array([test_x[0]]).shape
# student = 21
# print(test_y[student], model.predict(np.array([test_x[student]])))

64.0 [[65.67827]]


In [ ]:
mapaParametros = list(alumnos.columns)
mapaParametros.index('Horas Laboratorio')

5

In [ ]:
model = tf.keras.models.Sequential([
  # Capa de entrada
  keras.layers.Dense(128, activation='relu', input_shape=(36,)),
  # Capas internas 
  keras.layers.Dense(128, activation="relu"), 
  keras.layers.Dense(128, activation="relu"),

  keras.layers.Dropout(0.1),
  keras.layers.Dense(1, activation='relu')
  ])
model.compile(loss='mse', optimizer='adam', metrics=['mse'])

model = tf.keras.models.load_model('/content/pesosAPIS.h5')

In [ ]:
print(test_y[student], model.predict(np.array([test_x[student]])))

64.0 [[65.67827]]


In [ ]:
tuner.results_summary()

In [ ]:
best_model.summary()